services:
  database-jwt-es:
    container_name: jwt-es-database
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: asdf
      POSTGRES_DB: jwt-es
