spring:
  application:
    name: jwt-rsa
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
debug: false
trace: false